"""
SASTRA Research Finder - Core Package
"""

from app.core.config import (
    get_settings, Settings,
    SASTRA_SCHOOLS, DOCUMENT_TYPES, COUNTRY_PATTERNS, STOPWORDS,
    THEMATIC_AREAS, INTERDISCIPLINARY_COMBINATIONS, POPULAR_THEME_COMBINATIONS,
    JOURNAL_QUARTILES, CITATION_BINS, CITATION_BIN_LABELS, UI_COLORS
)

__all__ = [
    'get_settings', 'Settings',
    'SASTRA_SCHOOLS', 'DOCUMENT_TYPES', 'COUNTRY_PATTERNS', 'STOPWORDS',
    'THEMATIC_AREAS', 'INTERDISCIPLINARY_COMBINATIONS', 'POPULAR_THEME_COMBINATIONS',
    'JOURNAL_QUARTILES', 'CITATION_BINS', 'CITATION_BIN_LABELS', 'UI_COLORS'
]
